# Generated by Django 3.2.5 on 2022-08-03 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('TOYOTA', 'toyota'), ('CHEVROLET', 'chevrolet'), ('HONDA', 'honda'), ('FORD', 'ford'), ('FIAT', 'fiat'), ('JEEP', 'jeep'), ('VOLKSWAGEN', 'volkswagen'), ('VOLVO', 'volvo'), ('AUDI', 'audi'), ('LAND_ROVER', 'landrover'), ('LEXUS', 'lexus'), ('PORSHE', 'porshe'), ('BUGATTI', 'bugatti')], default='TOYOTA', max_length=20)),
                ('order_status', models.CharField(choices=[('PENDING', 'pending'), ('IN_TRANSIT', 'intransit'), ('DELIVERED', 'delivered')], default='PENDING', max_length=20)),
                ('quantity', models.IntegerField()),
                ('cars_description', models.TextField(blank=True, null=True)),
                ('cars_images', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
