# Generated by Django 3.2.5 on 2022-08-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='brand',
            field=models.CharField(choices=[('TOYOTA', 'toyota'), ('CHEVROLET', 'chevrolet'), ('HONDA', 'honda'), ('FORD', 'ford'), ('FIAT', 'fiat'), ('JEEP', 'jeep'), ('VOLKSWAGEN', 'volkswagen'), ('VOLVO', 'volvo'), ('AUDI', 'audi'), ('LAND_ROVER', 'landrover'), ('LEXUS', 'lexus'), ('PORSCHE', 'porsche'), ('BUGATTI', 'bugatti'), ('NISSAN', 'nissan'), ('JAGUAR', 'jaguar'), ('BENTLEY', 'bentley'), ('ROLLS_ROYCE', 'rollsroyce')], default='TOYOTA', max_length=20),
        ),
    ]
